name: Trigger auto deployment for cicd-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ 02-dockerfile ]
    paths:
    - '**'
    - '.github/workflows/cicd-frontend-AutoDeployTrigger-66738307-8319-472d-9e8f-9a5152a87148.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CICDFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CICDFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CICDFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: qnregistry.azurecr.io
          registryUsername: ${{ secrets.CICDFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CICDFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: cicd-frontend
          resourceGroup: qn-registry
          imageToBuild: qnregistry.azurecr.io/cicd-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


